
# PersistentVolumeClaim for state storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-rss-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
  storageClassName: local-path

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-rss-service
  labels:
    app: mail-rss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-rss
  template:
    metadata:
      labels:
        app: mail-rss
    spec:
      containers:
      - name: mail-rss
        image: zikriben/mail-rss-service:latest
        envFrom:
        - secretRef:
            name: mail-rss-secrets
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        volumeMounts:
        - name: data
          mountPath: /app/data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 120
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mail-rss-data

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mail-rss-service
  labels:
    app: mail-rss
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: mail-rss
